version: '3.3'
services:
    app:
      build: ./
      container_name: app
      command: bash -c ". venv/bin/activate
              && alembic upgrade head
              && python main.py"
      environment:
        - DB_URL=postgresql+asyncpg://postgres:admin@db:5432/question_service
        - TEST_DB_URL=postgresql+asyncpg://postgres:admin@db:5432/test_question_service
        - TEST_DB_NAME=test_question_service
      restart: always
      depends_on:
        - db
      ports:
        - 8000:8000

    db:
      user: root
      image: postgres:15
      restart: always
      volumes:
        - ./pg_db:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=question_service
      ports:
        - 5433:5432